### ISSUE TITLE
Property name nits

### ISSUE THREAD

**Issue by domenic** [rubberyuzu/bfcache-not-retored-reason#1]
Looking at the structures in https://github.com/rubberyuzu/bfcache-not-retored-reason/blob/main/NotRestoredReason.md#examples and comparing to https://w3ctag.github.io/design-principles/#casing-rules , I would suggest `url` and `id` instead of `URL` and `Id`. (Since they are the first/only word in the name.)

Also, in JavaScript we use `false` and `true`, not `False` and `True`.

**Comment by rubberyuzu** [comment]
Done, thanks!

**Comment by domenic** [comment]
Hmm, I think I might have misled you on the URL and Id properties. I think they should be lowercase `url` and `id`, since they are the first word in their name :)

**Comment by rubberyuzu** [comment]
Ah my bad! Fixed :) Thanks!
