### ISSUE TITLE
Cross-origin iframe name.

### ISSUE THREAD

**Issue by terjanq** [rubberyuzu/bfcache-not-retored-reason#4]
When reviewing the intent one thing brought my attention and that is a possibility of exposing cross-origin's frame name. It's not immediately clear whether it is an original `name` attribute from the frame, or the value is the actual frame's name which could be changed by an application. I guess that it's meant to be just `iframe.getAttribute('name')` which is fine. But just in case I wanted to point it out as a possible cross-origin leak (if for example the name was taken as `iframe.contentWindow.name`).

**Comment by rubberyuzu** [comment]
Thanks for the issue.
I actually forgot to update the document, and the current implementation hides all the information for cross-origin frames except for `bool blocked`. I agree that if we expose the name it is a potential leak.
Will update the document. Thanks again!

**Comment by rubberyuzu** [comment]
Sorry I was confused. Actually, name, id, src should be exposed for debugging. I will update the implementation and the explainer again.
But as you said, we are only exposing the original name instead of the updated name.

**Comment by terjanq** [comment]
In that case it should be fine :)
